/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkeletonExampleIndexRouteImport } from './routes/skeleton-example/index'
import { Route as ModalExampleIndexRouteImport } from './routes/modal-example/index'
import { Route as InputsExampleIndexRouteImport } from './routes/inputs-example/index'
import { Route as ButtonsExampleIndexRouteImport } from './routes/buttons-example/index'
import { Route as AvatarIndexRouteImport } from './routes/avatar/index'
import { Route as AccordionExampleIndexRouteImport } from './routes/accordion-example/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkeletonExampleIndexRoute = SkeletonExampleIndexRouteImport.update({
  id: '/skeleton-example/',
  path: '/skeleton-example/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModalExampleIndexRoute = ModalExampleIndexRouteImport.update({
  id: '/modal-example/',
  path: '/modal-example/',
  getParentRoute: () => rootRouteImport,
} as any)
const InputsExampleIndexRoute = InputsExampleIndexRouteImport.update({
  id: '/inputs-example/',
  path: '/inputs-example/',
  getParentRoute: () => rootRouteImport,
} as any)
const ButtonsExampleIndexRoute = ButtonsExampleIndexRouteImport.update({
  id: '/buttons-example/',
  path: '/buttons-example/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvatarIndexRoute = AvatarIndexRouteImport.update({
  id: '/avatar/',
  path: '/avatar/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccordionExampleIndexRoute = AccordionExampleIndexRouteImport.update({
  id: '/accordion-example/',
  path: '/accordion-example/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accordion-example': typeof AccordionExampleIndexRoute
  '/avatar': typeof AvatarIndexRoute
  '/buttons-example': typeof ButtonsExampleIndexRoute
  '/inputs-example': typeof InputsExampleIndexRoute
  '/modal-example': typeof ModalExampleIndexRoute
  '/skeleton-example': typeof SkeletonExampleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accordion-example': typeof AccordionExampleIndexRoute
  '/avatar': typeof AvatarIndexRoute
  '/buttons-example': typeof ButtonsExampleIndexRoute
  '/inputs-example': typeof InputsExampleIndexRoute
  '/modal-example': typeof ModalExampleIndexRoute
  '/skeleton-example': typeof SkeletonExampleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accordion-example/': typeof AccordionExampleIndexRoute
  '/avatar/': typeof AvatarIndexRoute
  '/buttons-example/': typeof ButtonsExampleIndexRoute
  '/inputs-example/': typeof InputsExampleIndexRoute
  '/modal-example/': typeof ModalExampleIndexRoute
  '/skeleton-example/': typeof SkeletonExampleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accordion-example'
    | '/avatar'
    | '/buttons-example'
    | '/inputs-example'
    | '/modal-example'
    | '/skeleton-example'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accordion-example'
    | '/avatar'
    | '/buttons-example'
    | '/inputs-example'
    | '/modal-example'
    | '/skeleton-example'
  id:
    | '__root__'
    | '/'
    | '/accordion-example/'
    | '/avatar/'
    | '/buttons-example/'
    | '/inputs-example/'
    | '/modal-example/'
    | '/skeleton-example/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccordionExampleIndexRoute: typeof AccordionExampleIndexRoute
  AvatarIndexRoute: typeof AvatarIndexRoute
  ButtonsExampleIndexRoute: typeof ButtonsExampleIndexRoute
  InputsExampleIndexRoute: typeof InputsExampleIndexRoute
  ModalExampleIndexRoute: typeof ModalExampleIndexRoute
  SkeletonExampleIndexRoute: typeof SkeletonExampleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skeleton-example/': {
      id: '/skeleton-example/'
      path: '/skeleton-example'
      fullPath: '/skeleton-example'
      preLoaderRoute: typeof SkeletonExampleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modal-example/': {
      id: '/modal-example/'
      path: '/modal-example'
      fullPath: '/modal-example'
      preLoaderRoute: typeof ModalExampleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inputs-example/': {
      id: '/inputs-example/'
      path: '/inputs-example'
      fullPath: '/inputs-example'
      preLoaderRoute: typeof InputsExampleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buttons-example/': {
      id: '/buttons-example/'
      path: '/buttons-example'
      fullPath: '/buttons-example'
      preLoaderRoute: typeof ButtonsExampleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avatar/': {
      id: '/avatar/'
      path: '/avatar'
      fullPath: '/avatar'
      preLoaderRoute: typeof AvatarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accordion-example/': {
      id: '/accordion-example/'
      path: '/accordion-example'
      fullPath: '/accordion-example'
      preLoaderRoute: typeof AccordionExampleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccordionExampleIndexRoute: AccordionExampleIndexRoute,
  AvatarIndexRoute: AvatarIndexRoute,
  ButtonsExampleIndexRoute: ButtonsExampleIndexRoute,
  InputsExampleIndexRoute: InputsExampleIndexRoute,
  ModalExampleIndexRoute: ModalExampleIndexRoute,
  SkeletonExampleIndexRoute: SkeletonExampleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
