/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ProtectedToasterIndexRouteImport } from './routes/_protected/toaster/index'
import { Route as ProtectedTextExampleIndexRouteImport } from './routes/_protected/text-example/index'
import { Route as ProtectedTanstackAiChatIndexRouteImport } from './routes/_protected/tanstack-ai-chat/index'
import { Route as ProtectedTabExampleIndexRouteImport } from './routes/_protected/tab-example/index'
import { Route as ProtectedSwitchExampleIndexRouteImport } from './routes/_protected/switch-example/index'
import { Route as ProtectedSkeletonExampleIndexRouteImport } from './routes/_protected/skeleton-example/index'
import { Route as ProtectedSelectExampleIndexRouteImport } from './routes/_protected/select-example/index'
import { Route as ProtectedRadioExampleIndexRouteImport } from './routes/_protected/radio-example/index'
import { Route as ProtectedModalExampleIndexRouteImport } from './routes/_protected/modal-example/index'
import { Route as ProtectedInputsExampleIndexRouteImport } from './routes/_protected/inputs-example/index'
import { Route as ProtectedFieldExampleIndexRouteImport } from './routes/_protected/field-example/index'
import { Route as ProtectedDrawerExampleIndexRouteImport } from './routes/_protected/drawer-example/index'
import { Route as ProtectedCheckboxExampleIndexRouteImport } from './routes/_protected/checkbox-example/index'
import { Route as ProtectedButtonsExampleIndexRouteImport } from './routes/_protected/buttons-example/index'
import { Route as ProtectedAvatarIndexRouteImport } from './routes/_protected/avatar/index'
import { Route as ProtectedAccordionExampleIndexRouteImport } from './routes/_protected/accordion-example/index'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedToasterIndexRoute = ProtectedToasterIndexRouteImport.update({
  id: '/toaster/',
  path: '/toaster/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedTextExampleIndexRoute =
  ProtectedTextExampleIndexRouteImport.update({
    id: '/text-example/',
    path: '/text-example/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedTanstackAiChatIndexRoute =
  ProtectedTanstackAiChatIndexRouteImport.update({
    id: '/tanstack-ai-chat/',
    path: '/tanstack-ai-chat/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedTabExampleIndexRoute =
  ProtectedTabExampleIndexRouteImport.update({
    id: '/tab-example/',
    path: '/tab-example/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSwitchExampleIndexRoute =
  ProtectedSwitchExampleIndexRouteImport.update({
    id: '/switch-example/',
    path: '/switch-example/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSkeletonExampleIndexRoute =
  ProtectedSkeletonExampleIndexRouteImport.update({
    id: '/skeleton-example/',
    path: '/skeleton-example/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSelectExampleIndexRoute =
  ProtectedSelectExampleIndexRouteImport.update({
    id: '/select-example/',
    path: '/select-example/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedRadioExampleIndexRoute =
  ProtectedRadioExampleIndexRouteImport.update({
    id: '/radio-example/',
    path: '/radio-example/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedModalExampleIndexRoute =
  ProtectedModalExampleIndexRouteImport.update({
    id: '/modal-example/',
    path: '/modal-example/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedInputsExampleIndexRoute =
  ProtectedInputsExampleIndexRouteImport.update({
    id: '/inputs-example/',
    path: '/inputs-example/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedFieldExampleIndexRoute =
  ProtectedFieldExampleIndexRouteImport.update({
    id: '/field-example/',
    path: '/field-example/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedDrawerExampleIndexRoute =
  ProtectedDrawerExampleIndexRouteImport.update({
    id: '/drawer-example/',
    path: '/drawer-example/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedCheckboxExampleIndexRoute =
  ProtectedCheckboxExampleIndexRouteImport.update({
    id: '/checkbox-example/',
    path: '/checkbox-example/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedButtonsExampleIndexRoute =
  ProtectedButtonsExampleIndexRouteImport.update({
    id: '/buttons-example/',
    path: '/buttons-example/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedAvatarIndexRoute = ProtectedAvatarIndexRouteImport.update({
  id: '/avatar/',
  path: '/avatar/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedAccordionExampleIndexRoute =
  ProtectedAccordionExampleIndexRouteImport.update({
    id: '/accordion-example/',
    path: '/accordion-example/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/accordion-example': typeof ProtectedAccordionExampleIndexRoute
  '/avatar': typeof ProtectedAvatarIndexRoute
  '/buttons-example': typeof ProtectedButtonsExampleIndexRoute
  '/checkbox-example': typeof ProtectedCheckboxExampleIndexRoute
  '/drawer-example': typeof ProtectedDrawerExampleIndexRoute
  '/field-example': typeof ProtectedFieldExampleIndexRoute
  '/inputs-example': typeof ProtectedInputsExampleIndexRoute
  '/modal-example': typeof ProtectedModalExampleIndexRoute
  '/radio-example': typeof ProtectedRadioExampleIndexRoute
  '/select-example': typeof ProtectedSelectExampleIndexRoute
  '/skeleton-example': typeof ProtectedSkeletonExampleIndexRoute
  '/switch-example': typeof ProtectedSwitchExampleIndexRoute
  '/tab-example': typeof ProtectedTabExampleIndexRoute
  '/tanstack-ai-chat': typeof ProtectedTanstackAiChatIndexRoute
  '/text-example': typeof ProtectedTextExampleIndexRoute
  '/toaster': typeof ProtectedToasterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/accordion-example': typeof ProtectedAccordionExampleIndexRoute
  '/avatar': typeof ProtectedAvatarIndexRoute
  '/buttons-example': typeof ProtectedButtonsExampleIndexRoute
  '/checkbox-example': typeof ProtectedCheckboxExampleIndexRoute
  '/drawer-example': typeof ProtectedDrawerExampleIndexRoute
  '/field-example': typeof ProtectedFieldExampleIndexRoute
  '/inputs-example': typeof ProtectedInputsExampleIndexRoute
  '/modal-example': typeof ProtectedModalExampleIndexRoute
  '/radio-example': typeof ProtectedRadioExampleIndexRoute
  '/select-example': typeof ProtectedSelectExampleIndexRoute
  '/skeleton-example': typeof ProtectedSkeletonExampleIndexRoute
  '/switch-example': typeof ProtectedSwitchExampleIndexRoute
  '/tab-example': typeof ProtectedTabExampleIndexRoute
  '/tanstack-ai-chat': typeof ProtectedTanstackAiChatIndexRoute
  '/text-example': typeof ProtectedTextExampleIndexRoute
  '/toaster': typeof ProtectedToasterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/_protected/accordion-example/': typeof ProtectedAccordionExampleIndexRoute
  '/_protected/avatar/': typeof ProtectedAvatarIndexRoute
  '/_protected/buttons-example/': typeof ProtectedButtonsExampleIndexRoute
  '/_protected/checkbox-example/': typeof ProtectedCheckboxExampleIndexRoute
  '/_protected/drawer-example/': typeof ProtectedDrawerExampleIndexRoute
  '/_protected/field-example/': typeof ProtectedFieldExampleIndexRoute
  '/_protected/inputs-example/': typeof ProtectedInputsExampleIndexRoute
  '/_protected/modal-example/': typeof ProtectedModalExampleIndexRoute
  '/_protected/radio-example/': typeof ProtectedRadioExampleIndexRoute
  '/_protected/select-example/': typeof ProtectedSelectExampleIndexRoute
  '/_protected/skeleton-example/': typeof ProtectedSkeletonExampleIndexRoute
  '/_protected/switch-example/': typeof ProtectedSwitchExampleIndexRoute
  '/_protected/tab-example/': typeof ProtectedTabExampleIndexRoute
  '/_protected/tanstack-ai-chat/': typeof ProtectedTanstackAiChatIndexRoute
  '/_protected/text-example/': typeof ProtectedTextExampleIndexRoute
  '/_protected/toaster/': typeof ProtectedToasterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/accordion-example'
    | '/avatar'
    | '/buttons-example'
    | '/checkbox-example'
    | '/drawer-example'
    | '/field-example'
    | '/inputs-example'
    | '/modal-example'
    | '/radio-example'
    | '/select-example'
    | '/skeleton-example'
    | '/switch-example'
    | '/tab-example'
    | '/tanstack-ai-chat'
    | '/text-example'
    | '/toaster'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/accordion-example'
    | '/avatar'
    | '/buttons-example'
    | '/checkbox-example'
    | '/drawer-example'
    | '/field-example'
    | '/inputs-example'
    | '/modal-example'
    | '/radio-example'
    | '/select-example'
    | '/skeleton-example'
    | '/switch-example'
    | '/tab-example'
    | '/tanstack-ai-chat'
    | '/text-example'
    | '/toaster'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/auth/login'
    | '/_protected/accordion-example/'
    | '/_protected/avatar/'
    | '/_protected/buttons-example/'
    | '/_protected/checkbox-example/'
    | '/_protected/drawer-example/'
    | '/_protected/field-example/'
    | '/_protected/inputs-example/'
    | '/_protected/modal-example/'
    | '/_protected/radio-example/'
    | '/_protected/select-example/'
    | '/_protected/skeleton-example/'
    | '/_protected/switch-example/'
    | '/_protected/tab-example/'
    | '/_protected/tanstack-ai-chat/'
    | '/_protected/text-example/'
    | '/_protected/toaster/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/toaster/': {
      id: '/_protected/toaster/'
      path: '/toaster'
      fullPath: '/toaster'
      preLoaderRoute: typeof ProtectedToasterIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/text-example/': {
      id: '/_protected/text-example/'
      path: '/text-example'
      fullPath: '/text-example'
      preLoaderRoute: typeof ProtectedTextExampleIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/tanstack-ai-chat/': {
      id: '/_protected/tanstack-ai-chat/'
      path: '/tanstack-ai-chat'
      fullPath: '/tanstack-ai-chat'
      preLoaderRoute: typeof ProtectedTanstackAiChatIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/tab-example/': {
      id: '/_protected/tab-example/'
      path: '/tab-example'
      fullPath: '/tab-example'
      preLoaderRoute: typeof ProtectedTabExampleIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/switch-example/': {
      id: '/_protected/switch-example/'
      path: '/switch-example'
      fullPath: '/switch-example'
      preLoaderRoute: typeof ProtectedSwitchExampleIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/skeleton-example/': {
      id: '/_protected/skeleton-example/'
      path: '/skeleton-example'
      fullPath: '/skeleton-example'
      preLoaderRoute: typeof ProtectedSkeletonExampleIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/select-example/': {
      id: '/_protected/select-example/'
      path: '/select-example'
      fullPath: '/select-example'
      preLoaderRoute: typeof ProtectedSelectExampleIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/radio-example/': {
      id: '/_protected/radio-example/'
      path: '/radio-example'
      fullPath: '/radio-example'
      preLoaderRoute: typeof ProtectedRadioExampleIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/modal-example/': {
      id: '/_protected/modal-example/'
      path: '/modal-example'
      fullPath: '/modal-example'
      preLoaderRoute: typeof ProtectedModalExampleIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/inputs-example/': {
      id: '/_protected/inputs-example/'
      path: '/inputs-example'
      fullPath: '/inputs-example'
      preLoaderRoute: typeof ProtectedInputsExampleIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/field-example/': {
      id: '/_protected/field-example/'
      path: '/field-example'
      fullPath: '/field-example'
      preLoaderRoute: typeof ProtectedFieldExampleIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/drawer-example/': {
      id: '/_protected/drawer-example/'
      path: '/drawer-example'
      fullPath: '/drawer-example'
      preLoaderRoute: typeof ProtectedDrawerExampleIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/checkbox-example/': {
      id: '/_protected/checkbox-example/'
      path: '/checkbox-example'
      fullPath: '/checkbox-example'
      preLoaderRoute: typeof ProtectedCheckboxExampleIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/buttons-example/': {
      id: '/_protected/buttons-example/'
      path: '/buttons-example'
      fullPath: '/buttons-example'
      preLoaderRoute: typeof ProtectedButtonsExampleIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/avatar/': {
      id: '/_protected/avatar/'
      path: '/avatar'
      fullPath: '/avatar'
      preLoaderRoute: typeof ProtectedAvatarIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/accordion-example/': {
      id: '/_protected/accordion-example/'
      path: '/accordion-example'
      fullPath: '/accordion-example'
      preLoaderRoute: typeof ProtectedAccordionExampleIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedAccordionExampleIndexRoute: typeof ProtectedAccordionExampleIndexRoute
  ProtectedAvatarIndexRoute: typeof ProtectedAvatarIndexRoute
  ProtectedButtonsExampleIndexRoute: typeof ProtectedButtonsExampleIndexRoute
  ProtectedCheckboxExampleIndexRoute: typeof ProtectedCheckboxExampleIndexRoute
  ProtectedDrawerExampleIndexRoute: typeof ProtectedDrawerExampleIndexRoute
  ProtectedFieldExampleIndexRoute: typeof ProtectedFieldExampleIndexRoute
  ProtectedInputsExampleIndexRoute: typeof ProtectedInputsExampleIndexRoute
  ProtectedModalExampleIndexRoute: typeof ProtectedModalExampleIndexRoute
  ProtectedRadioExampleIndexRoute: typeof ProtectedRadioExampleIndexRoute
  ProtectedSelectExampleIndexRoute: typeof ProtectedSelectExampleIndexRoute
  ProtectedSkeletonExampleIndexRoute: typeof ProtectedSkeletonExampleIndexRoute
  ProtectedSwitchExampleIndexRoute: typeof ProtectedSwitchExampleIndexRoute
  ProtectedTabExampleIndexRoute: typeof ProtectedTabExampleIndexRoute
  ProtectedTanstackAiChatIndexRoute: typeof ProtectedTanstackAiChatIndexRoute
  ProtectedTextExampleIndexRoute: typeof ProtectedTextExampleIndexRoute
  ProtectedToasterIndexRoute: typeof ProtectedToasterIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedAccordionExampleIndexRoute: ProtectedAccordionExampleIndexRoute,
  ProtectedAvatarIndexRoute: ProtectedAvatarIndexRoute,
  ProtectedButtonsExampleIndexRoute: ProtectedButtonsExampleIndexRoute,
  ProtectedCheckboxExampleIndexRoute: ProtectedCheckboxExampleIndexRoute,
  ProtectedDrawerExampleIndexRoute: ProtectedDrawerExampleIndexRoute,
  ProtectedFieldExampleIndexRoute: ProtectedFieldExampleIndexRoute,
  ProtectedInputsExampleIndexRoute: ProtectedInputsExampleIndexRoute,
  ProtectedModalExampleIndexRoute: ProtectedModalExampleIndexRoute,
  ProtectedRadioExampleIndexRoute: ProtectedRadioExampleIndexRoute,
  ProtectedSelectExampleIndexRoute: ProtectedSelectExampleIndexRoute,
  ProtectedSkeletonExampleIndexRoute: ProtectedSkeletonExampleIndexRoute,
  ProtectedSwitchExampleIndexRoute: ProtectedSwitchExampleIndexRoute,
  ProtectedTabExampleIndexRoute: ProtectedTabExampleIndexRoute,
  ProtectedTanstackAiChatIndexRoute: ProtectedTanstackAiChatIndexRoute,
  ProtectedTextExampleIndexRoute: ProtectedTextExampleIndexRoute,
  ProtectedToasterIndexRoute: ProtectedToasterIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
