/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToasterIndexRouteImport } from './routes/toaster/index'
import { Route as TextExampleIndexRouteImport } from './routes/text-example/index'
import { Route as TanstackAiChatIndexRouteImport } from './routes/tanstack-ai-chat/index'
import { Route as TabExampleIndexRouteImport } from './routes/tab-example/index'
import { Route as SwitchExampleIndexRouteImport } from './routes/switch-example/index'
import { Route as SkeletonExampleIndexRouteImport } from './routes/skeleton-example/index'
import { Route as SelectExampleIndexRouteImport } from './routes/select-example/index'
import { Route as ModalExampleIndexRouteImport } from './routes/modal-example/index'
import { Route as InputsExampleIndexRouteImport } from './routes/inputs-example/index'
import { Route as DrawerExampleIndexRouteImport } from './routes/drawer-example/index'
import { Route as ButtonsExampleIndexRouteImport } from './routes/buttons-example/index'
import { Route as AvatarIndexRouteImport } from './routes/avatar/index'
import { Route as AccordionExampleIndexRouteImport } from './routes/accordion-example/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToasterIndexRoute = ToasterIndexRouteImport.update({
  id: '/toaster/',
  path: '/toaster/',
  getParentRoute: () => rootRouteImport,
} as any)
const TextExampleIndexRoute = TextExampleIndexRouteImport.update({
  id: '/text-example/',
  path: '/text-example/',
  getParentRoute: () => rootRouteImport,
} as any)
const TanstackAiChatIndexRoute = TanstackAiChatIndexRouteImport.update({
  id: '/tanstack-ai-chat/',
  path: '/tanstack-ai-chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const TabExampleIndexRoute = TabExampleIndexRouteImport.update({
  id: '/tab-example/',
  path: '/tab-example/',
  getParentRoute: () => rootRouteImport,
} as any)
const SwitchExampleIndexRoute = SwitchExampleIndexRouteImport.update({
  id: '/switch-example/',
  path: '/switch-example/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkeletonExampleIndexRoute = SkeletonExampleIndexRouteImport.update({
  id: '/skeleton-example/',
  path: '/skeleton-example/',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectExampleIndexRoute = SelectExampleIndexRouteImport.update({
  id: '/select-example/',
  path: '/select-example/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModalExampleIndexRoute = ModalExampleIndexRouteImport.update({
  id: '/modal-example/',
  path: '/modal-example/',
  getParentRoute: () => rootRouteImport,
} as any)
const InputsExampleIndexRoute = InputsExampleIndexRouteImport.update({
  id: '/inputs-example/',
  path: '/inputs-example/',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawerExampleIndexRoute = DrawerExampleIndexRouteImport.update({
  id: '/drawer-example/',
  path: '/drawer-example/',
  getParentRoute: () => rootRouteImport,
} as any)
const ButtonsExampleIndexRoute = ButtonsExampleIndexRouteImport.update({
  id: '/buttons-example/',
  path: '/buttons-example/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvatarIndexRoute = AvatarIndexRouteImport.update({
  id: '/avatar/',
  path: '/avatar/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccordionExampleIndexRoute = AccordionExampleIndexRouteImport.update({
  id: '/accordion-example/',
  path: '/accordion-example/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accordion-example': typeof AccordionExampleIndexRoute
  '/avatar': typeof AvatarIndexRoute
  '/buttons-example': typeof ButtonsExampleIndexRoute
  '/drawer-example': typeof DrawerExampleIndexRoute
  '/inputs-example': typeof InputsExampleIndexRoute
  '/modal-example': typeof ModalExampleIndexRoute
  '/select-example': typeof SelectExampleIndexRoute
  '/skeleton-example': typeof SkeletonExampleIndexRoute
  '/switch-example': typeof SwitchExampleIndexRoute
  '/tab-example': typeof TabExampleIndexRoute
  '/tanstack-ai-chat': typeof TanstackAiChatIndexRoute
  '/text-example': typeof TextExampleIndexRoute
  '/toaster': typeof ToasterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accordion-example': typeof AccordionExampleIndexRoute
  '/avatar': typeof AvatarIndexRoute
  '/buttons-example': typeof ButtonsExampleIndexRoute
  '/drawer-example': typeof DrawerExampleIndexRoute
  '/inputs-example': typeof InputsExampleIndexRoute
  '/modal-example': typeof ModalExampleIndexRoute
  '/select-example': typeof SelectExampleIndexRoute
  '/skeleton-example': typeof SkeletonExampleIndexRoute
  '/switch-example': typeof SwitchExampleIndexRoute
  '/tab-example': typeof TabExampleIndexRoute
  '/tanstack-ai-chat': typeof TanstackAiChatIndexRoute
  '/text-example': typeof TextExampleIndexRoute
  '/toaster': typeof ToasterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accordion-example/': typeof AccordionExampleIndexRoute
  '/avatar/': typeof AvatarIndexRoute
  '/buttons-example/': typeof ButtonsExampleIndexRoute
  '/drawer-example/': typeof DrawerExampleIndexRoute
  '/inputs-example/': typeof InputsExampleIndexRoute
  '/modal-example/': typeof ModalExampleIndexRoute
  '/select-example/': typeof SelectExampleIndexRoute
  '/skeleton-example/': typeof SkeletonExampleIndexRoute
  '/switch-example/': typeof SwitchExampleIndexRoute
  '/tab-example/': typeof TabExampleIndexRoute
  '/tanstack-ai-chat/': typeof TanstackAiChatIndexRoute
  '/text-example/': typeof TextExampleIndexRoute
  '/toaster/': typeof ToasterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accordion-example'
    | '/avatar'
    | '/buttons-example'
    | '/drawer-example'
    | '/inputs-example'
    | '/modal-example'
    | '/select-example'
    | '/skeleton-example'
    | '/switch-example'
    | '/tab-example'
    | '/tanstack-ai-chat'
    | '/text-example'
    | '/toaster'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accordion-example'
    | '/avatar'
    | '/buttons-example'
    | '/drawer-example'
    | '/inputs-example'
    | '/modal-example'
    | '/select-example'
    | '/skeleton-example'
    | '/switch-example'
    | '/tab-example'
    | '/tanstack-ai-chat'
    | '/text-example'
    | '/toaster'
  id:
    | '__root__'
    | '/'
    | '/accordion-example/'
    | '/avatar/'
    | '/buttons-example/'
    | '/drawer-example/'
    | '/inputs-example/'
    | '/modal-example/'
    | '/select-example/'
    | '/skeleton-example/'
    | '/switch-example/'
    | '/tab-example/'
    | '/tanstack-ai-chat/'
    | '/text-example/'
    | '/toaster/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccordionExampleIndexRoute: typeof AccordionExampleIndexRoute
  AvatarIndexRoute: typeof AvatarIndexRoute
  ButtonsExampleIndexRoute: typeof ButtonsExampleIndexRoute
  DrawerExampleIndexRoute: typeof DrawerExampleIndexRoute
  InputsExampleIndexRoute: typeof InputsExampleIndexRoute
  ModalExampleIndexRoute: typeof ModalExampleIndexRoute
  SelectExampleIndexRoute: typeof SelectExampleIndexRoute
  SkeletonExampleIndexRoute: typeof SkeletonExampleIndexRoute
  SwitchExampleIndexRoute: typeof SwitchExampleIndexRoute
  TabExampleIndexRoute: typeof TabExampleIndexRoute
  TanstackAiChatIndexRoute: typeof TanstackAiChatIndexRoute
  TextExampleIndexRoute: typeof TextExampleIndexRoute
  ToasterIndexRoute: typeof ToasterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toaster/': {
      id: '/toaster/'
      path: '/toaster'
      fullPath: '/toaster'
      preLoaderRoute: typeof ToasterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-example/': {
      id: '/text-example/'
      path: '/text-example'
      fullPath: '/text-example'
      preLoaderRoute: typeof TextExampleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tanstack-ai-chat/': {
      id: '/tanstack-ai-chat/'
      path: '/tanstack-ai-chat'
      fullPath: '/tanstack-ai-chat'
      preLoaderRoute: typeof TanstackAiChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tab-example/': {
      id: '/tab-example/'
      path: '/tab-example'
      fullPath: '/tab-example'
      preLoaderRoute: typeof TabExampleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/switch-example/': {
      id: '/switch-example/'
      path: '/switch-example'
      fullPath: '/switch-example'
      preLoaderRoute: typeof SwitchExampleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skeleton-example/': {
      id: '/skeleton-example/'
      path: '/skeleton-example'
      fullPath: '/skeleton-example'
      preLoaderRoute: typeof SkeletonExampleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-example/': {
      id: '/select-example/'
      path: '/select-example'
      fullPath: '/select-example'
      preLoaderRoute: typeof SelectExampleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modal-example/': {
      id: '/modal-example/'
      path: '/modal-example'
      fullPath: '/modal-example'
      preLoaderRoute: typeof ModalExampleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inputs-example/': {
      id: '/inputs-example/'
      path: '/inputs-example'
      fullPath: '/inputs-example'
      preLoaderRoute: typeof InputsExampleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawer-example/': {
      id: '/drawer-example/'
      path: '/drawer-example'
      fullPath: '/drawer-example'
      preLoaderRoute: typeof DrawerExampleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buttons-example/': {
      id: '/buttons-example/'
      path: '/buttons-example'
      fullPath: '/buttons-example'
      preLoaderRoute: typeof ButtonsExampleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avatar/': {
      id: '/avatar/'
      path: '/avatar'
      fullPath: '/avatar'
      preLoaderRoute: typeof AvatarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accordion-example/': {
      id: '/accordion-example/'
      path: '/accordion-example'
      fullPath: '/accordion-example'
      preLoaderRoute: typeof AccordionExampleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccordionExampleIndexRoute: AccordionExampleIndexRoute,
  AvatarIndexRoute: AvatarIndexRoute,
  ButtonsExampleIndexRoute: ButtonsExampleIndexRoute,
  DrawerExampleIndexRoute: DrawerExampleIndexRoute,
  InputsExampleIndexRoute: InputsExampleIndexRoute,
  ModalExampleIndexRoute: ModalExampleIndexRoute,
  SelectExampleIndexRoute: SelectExampleIndexRoute,
  SkeletonExampleIndexRoute: SkeletonExampleIndexRoute,
  SwitchExampleIndexRoute: SwitchExampleIndexRoute,
  TabExampleIndexRoute: TabExampleIndexRoute,
  TanstackAiChatIndexRoute: TanstackAiChatIndexRoute,
  TextExampleIndexRoute: TextExampleIndexRoute,
  ToasterIndexRoute: ToasterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
